<?php

// CITAT
function kopparpannan_register_post_type() {

	$args = array (
		'label' => esc_html__( 'Citat', 'text-domain' ),
		'labels' => array(
			'menu_name' => esc_html__( 'Citat', 'text-domain' ),
			'name_admin_bar' => esc_html__( 'Citat', 'text-domain' ),
			'add_new' => esc_html__( 'Add new', 'text-domain' ),
			'add_new_item' => esc_html__( 'Add new Citat', 'text-domain' ),
			'new_item' => esc_html__( 'New Citat', 'text-domain' ),
			'edit_item' => esc_html__( 'Edit Citat', 'text-domain' ),
			'view_item' => esc_html__( 'View Citat', 'text-domain' ),
			'update_item' => esc_html__( 'Update Citat', 'text-domain' ),
			'all_items' => esc_html__( 'All Citat', 'text-domain' ),
			'search_items' => esc_html__( 'Search Citat', 'text-domain' ),
			'parent_item_colon' => esc_html__( 'Parent Citat', 'text-domain' ),
			'not_found' => esc_html__( 'No Citat found', 'text-domain' ),
			'not_found_in_trash' => esc_html__( 'No Citat found in Trash', 'text-domain' ),
			'name' => esc_html__( 'Citat', 'text-domain' ),
			'singular_name' => esc_html__( 'Citat', 'text-domain' ),
		),
		'public' => true,
		'exclude_from_search' => false,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'show_in_admin_bar' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-star-filled',
		'capability_type' => 'post',
		'hierarchical' => false,
		'has_archive' => true,
		'query_var' => true,
		'can_export' => true,
		'rewrite_no_front' => false,
		'supports' => array('title'),
		'rewrite' => true,
	);

	register_post_type( 'citat', $args );

	$args = array (
		'label' => esc_html__( 'Gästanmälningar', 'text-domain' ),
		'labels' => array(
			'menu_name' => esc_html__( 'Gästanmälningar', 'text-domain' ),
			'name_admin_bar' => esc_html__( 'Gästanmälning', 'text-domain' ),
			'add_new' => esc_html__( 'Add new', 'text-domain' ),
			'add_new_item' => esc_html__( 'Add new Gästanmälning', 'text-domain' ),
			'new_item' => esc_html__( 'New Gästanmälning', 'text-domain' ),
			'edit_item' => esc_html__( 'Edit Gästanmälning', 'text-domain' ),
			'view_item' => esc_html__( 'View Gästanmälning', 'text-domain' ),
			'update_item' => esc_html__( 'Update Gästanmälning', 'text-domain' ),
			'all_items' => esc_html__( 'All Gästanmälningar', 'text-domain' ),
			'search_items' => esc_html__( 'Search Gästanmälningar', 'text-domain' ),
			'parent_item_colon' => esc_html__( 'Parent Gästanmälning', 'text-domain' ),
			'not_found' => esc_html__( 'No Gästanmälningar found', 'text-domain' ),
			'not_found_in_trash' => esc_html__( 'No Gästanmälningar found in Trash', 'text-domain' ),
			'name' => esc_html__( 'Gästanmälningar', 'text-domain' ),
			'singular_name' => esc_html__( 'Gästanmälning', 'text-domain' ),
		),
		'public' => true,
		'exclude_from_search' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'show_in_admin_bar' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-groups',
		'capability_type' => 'post',
		'hierarchical' => false,
		'has_archive' => true,
		'query_var' => true,
		'can_export' => true,
		'rewrite_no_front' => false,
		'rewrite' => true,
	);

	register_post_type( 'gastanmalning', $args );

	$args = array (
		'label' => esc_html__( 'Medlemsanmälningar', 'text-domain' ),
		'labels' => array(
			'menu_name' => esc_html__( 'Medlemsanmäln.', 'text-domain' ),
			'name_admin_bar' => esc_html__( 'Medlemsanmälning', 'text-domain' ),
			'add_new' => esc_html__( 'Add new', 'text-domain' ),
			'add_new_item' => esc_html__( 'Add new Medlemsanmälning', 'text-domain' ),
			'new_item' => esc_html__( 'New Medlemsanmälning', 'text-domain' ),
			'edit_item' => esc_html__( 'Edit Medlemsanmälning', 'text-domain' ),
			'view_item' => esc_html__( 'View Medlemsanmälning', 'text-domain' ),
			'update_item' => esc_html__( 'Update Medlemsanmälning', 'text-domain' ),
			'all_items' => esc_html__( 'All Medlemsanmälningar', 'text-domain' ),
			'search_items' => esc_html__( 'Search Medlemsanmälningar', 'text-domain' ),
			'parent_item_colon' => esc_html__( 'Parent Medlemsanmälning', 'text-domain' ),
			'not_found' => esc_html__( 'No Medlemsanmälningar found', 'text-domain' ),
			'not_found_in_trash' => esc_html__( 'No Medlemsanmälningar found in Trash', 'text-domain' ),
			'name' => esc_html__( 'Medlemsanmälningar', 'text-domain' ),
			'singular_name' => esc_html__( 'Medlemsanmälning', 'text-domain' ),
		),
		'public' => true,
		'exclude_from_search' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'show_in_admin_bar' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-users',
		'capability_type' => 'post',
		'hierarchical' => false,
		'has_archive' => true,
		'query_var' => true,
		'can_export' => true,
		'rewrite_no_front' => false,
		'supports' => array(
			'title',
			'editor',
			'thumbnail',
		),
		'rewrite' => true,
	);

	register_post_type( 'medlemsanmalning', $args );

	$args = array (
		'label' => esc_html__( 'Medlemskandidater', 'text-domain' ),
		'labels' => array(
			'menu_name' => esc_html__( 'Medlemskandidater', 'text-domain' ),
			'name_admin_bar' => esc_html__( 'Medlemskandidat', 'text-domain' ),
			'add_new' => esc_html__( 'Add new', 'text-domain' ),
			'add_new_item' => esc_html__( 'Add new Medlemskandidat', 'text-domain' ),
			'new_item' => esc_html__( 'New Medlemskandidat', 'text-domain' ),
			'edit_item' => esc_html__( 'Edit Medlemskandidat', 'text-domain' ),
			'view_item' => esc_html__( 'View Medlemskandidat', 'text-domain' ),
			'update_item' => esc_html__( 'Update Medlemskandidat', 'text-domain' ),
			'all_items' => esc_html__( 'All Medlemskandidater', 'text-domain' ),
			'search_items' => esc_html__( 'Search Medlemskandidater', 'text-domain' ),
			'parent_item_colon' => esc_html__( 'Parent Medlemskandidat', 'text-domain' ),
			'not_found' => esc_html__( 'No Medlemskandidater found', 'text-domain' ),
			'not_found_in_trash' => esc_html__( 'No Medlemskandidater found in Trash', 'text-domain' ),
			'name' => esc_html__( 'Medlemskandidater', 'text-domain' ),
			'singular_name' => esc_html__( 'Medlemskandidat', 'text-domain' ),
		),
		'public' => true,
		'exclude_from_search' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'show_in_admin_bar' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-smiley',
		'capability_type' => 'post',
		'hierarchical' => false,
		'has_archive' => true,
		'query_var' => true,
		'can_export' => true,
		'rewrite_no_front' => false,
		'rewrite' => true,
	);

	register_post_type( 'kp-medlemskandidat', $args );

	$args = array (
		'label' => esc_html__( 'Whiskybetyg', 'kopparpannan' ),
		'labels' => array(
			'menu_name' => esc_html__( 'Whiskybetyg', 'kopparpannan' ),
			'name_admin_bar' => esc_html__( 'Whiskybetyg', 'kopparpannan' ),
			'add_new' => esc_html__( 'Add new', 'kopparpannan' ),
			'add_new_item' => esc_html__( 'Add new Whiskybetyg', 'kopparpannan' ),
			'new_item' => esc_html__( 'New Whiskybetyg', 'kopparpannan' ),
			'edit_item' => esc_html__( 'Edit Whiskybetyg', 'kopparpannan' ),
			'view_item' => esc_html__( 'View Whiskybetyg', 'kopparpannan' ),
			'update_item' => esc_html__( 'Update Whiskybetyg', 'kopparpannan' ),
			'all_items' => esc_html__( 'All Whiskybetyg', 'kopparpannan' ),
			'search_items' => esc_html__( 'Search Whiskybetyg', 'kopparpannan' ),
			'parent_item_colon' => esc_html__( 'Parent Whiskybetyg', 'kopparpannan' ),
			'not_found' => esc_html__( 'No Whiskybetyg found', 'kopparpannan' ),
			'not_found_in_trash' => esc_html__( 'No Whiskybetyg found in Trash', 'kopparpannan' ),
			'name' => esc_html__( 'Whiskybetyg', 'kopparpannan' ),
			'singular_name' => esc_html__( 'Whiskybetyg', 'kopparpannan' ),
		),
		'public' => true,
		'exclude_from_search' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'show_in_admin_bar' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-chart-line',
		'capability_type' => 'post',
		'hierarchical' => false,
		'has_archive' => true,
		'query_var' => true,
		'can_export' => true,
		'rewrite_no_front' => false,
		'supports' => array(
			'revisions',
			'title',
		),
		'rewrite' => true,
	);

	register_post_type( 'kp-whiskybetyg', $args );

	$args = array (
		'label' => esc_html__( 'Events', 'text-domain' ),
		'labels' => array(
			'menu_name' => esc_html__( 'Events', 'text-domain' ),
			'name_admin_bar' => esc_html__( 'Event', 'text-domain' ),
			'add_new' => esc_html__( 'Lägg till nytt', 'text-domain' ),
			'add_new_item' => esc_html__( 'Lägg till nytt Event', 'text-domain' ),
			'new_item' => esc_html__( 'Nytt Event', 'text-domain' ),
			'edit_item' => esc_html__( 'Editera Event', 'text-domain' ),
			'view_item' => esc_html__( 'Visa Event', 'text-domain' ),
			'update_item' => esc_html__( 'Update Event', 'text-domain' ),
			'all_items' => esc_html__( 'Alla Events', 'text-domain' ),
			'search_items' => esc_html__( 'Sök Events', 'text-domain' ),
			'parent_item_colon' => esc_html__( 'Överliggande Event', 'text-domain' ),
			'not_found' => esc_html__( 'Inga Events hittades', 'text-domain' ),
			'not_found_in_trash' => esc_html__( 'Inga Events hittades i soptunnan.', 'text-domain' ),
			'name' => esc_html__( 'Events', 'text-domain' ),
			'singular_name' => esc_html__( 'Event', 'text-domain' ),
		),
		'public' => true,
		'exclude_from_search' => false,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'show_in_menu' => true,
		'show_in_admin_bar' => true,
		'show_in_rest' => true,
		'capability_type' => 'post',
		'hierarchical' => true,
		'has_archive' => true,
		'query_var' => true,
		'can_export' => true,
		'rewrite_no_front' => false,
		'supports' => array(
			'title',
			'editor',
			'thumbnail',
			'author',
			'trackbacks',
			'custom-fields',
			'comments',
			'revisions',
			'page-attributes',
		),
		'menu_icon' => 'dashicons-calendar-alt',
		'rest_base' => 'event',
		'rewrite' => true,
	);

	register_post_type( 'kopparpannan-event', $args );

	$args = array (
		'label' => esc_html__( 'Whisky', 'text-domain' ),
		'labels' => array(
			'menu_name' => esc_html__( 'Whisky', 'text-domain' ),
			'name_admin_bar' => esc_html__( 'Whisky', 'text-domain' ),
			'add_new' => esc_html__( 'Registrera ny', 'text-domain' ),
			'add_new_item' => esc_html__( 'Registrera ny Whisky', 'text-domain' ),
			'new_item' => esc_html__( 'Ny Whisky', 'text-domain' ),
			'edit_item' => esc_html__( 'Ändra Whisky', 'text-domain' ),
			'view_item' => esc_html__( 'Visa Whisky', 'text-domain' ),
			'update_item' => esc_html__( 'Update Whisky', 'text-domain' ),
			'all_items' => esc_html__( 'All Whisky', 'text-domain' ),
			'search_items' => esc_html__( 'Sök Whisky', 'text-domain' ),
			'parent_item_colon' => esc_html__( 'Parent Whisky', 'text-domain' ),
			'not_found' => esc_html__( 'Ingen sådan Whisky hittades', 'text-domain' ),
			'not_found_in_trash' => esc_html__( 'Ingen sådan Whisky fanns kastad', 'text-domain' ),
			'name' => esc_html__( 'Whisky', 'text-domain' ),
			'singular_name' => esc_html__( 'Whisky', 'text-domain' ),
		),
		'public' => true,
		'description' => 'En beskrivning av en whisky.',
		'exclude_from_search' => false,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'show_in_menu' => true,
		'show_in_admin_bar' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-awards',
		'capability_type' => 'post',
		'hierarchical' => false,
		'has_archive' => true,
		'query_var' => true,
		'can_export' => true,
		'rewrite_no_front' => false,
		'supports' => array(
			'title',
			'editor',
			'author',
			'thumbnail',
			'custom-fields',
			'comments',
		),
		'taxonomies' => array(
			'category',
		),
		'rest_base' => 'whisky',
		'rewrite' => true,
	);

	register_post_type( 'kopparpannan-whisky', $args );
}

add_action( 'init', 'kopparpannan_register_post_type' );